# Generated by Django 5.0.7 on 2024-08-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
    ]
