# Generated by Django 5.1 on 2024-08-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_alter_airline_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
